version: '3.1'

services:

  mysql:
    image: mysql:8.0.13
    command: --init-file /db-dump/dump.sql
    environment:
      MYSQL_DATABASE: telegram
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-mount:/var/lib/mysql
    ports:
      - 3306:3005